### ISSUE TITLE
Unable to Scrape

### ISSUE THREAD

**Issue by setite** [FantasyFootballAnalytics/ffanalytics#1]
Not sure if this is something only happening to me but I can't figure out whats wrong. Below is what happens when I try to scrape.

    > my_scrape <- scrape_data(src = c("CBS", "ESPN", "Yahoo"), 
    +                          pos = c("QB", "RB", "WR", "TE", "DST"),
    +                          season = 2018, week = 0)
    Scraping QB projections from 
     https://www.cbssports.com/fantasy/football/stats/weeklyprojections/QB/season/avg/standard?   print_rows=9999 
     Error in make_df_colnames(data_table) : 
      could not find function "make_df_colnames"

**Comment by MrDAndersen** [comment]
This should be fixed now.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
