### ISSUE TITLE
projections_table function triggers multiple errors

### ISSUE THREAD

**Issue by consumptionltd** [FantasyFootballAnalytics/ffanalytics#10]
`> my_projections <-  projections_table(my_scrape)`

> Error in (function (x, strict = TRUE)  : 
>   the argument has already been evaluated
> In addition: Warning messages:
> 1: Unknown variables: `id`, `data_src` 
> 2: Unknown variables: `id`, `data_src`

**Comment by consumptionltd** [comment]
to replicate, follow example code in README exactly

**Comment by MrDAndersen** [comment]
This was fixed in #6. Please reinstall the package.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
