### ISSUE TITLE
Issue Installing Package

### ISSUE THREAD

**Issue by bonddr** [FantasyFootballAnalytics/ffanalytics#103]
I've seen this issue opened and closed before, but when I try to use the following to install:

_devtools::install_github("FantasyFootballAnalytics/ffanalytics")_

I receive the following error:

_Error: (converted from warning) package 'httr' was built under R version 4.0.5
Execution halted
ERROR: lazy loading failed for package 'ffanalytics'
* removing 'C:/Users/---/R/win-library/4.0/ffanalytics'
installation of package C:/Users/---/ffanalytics_2.0.7.0001.tar.gz� had non-zero exit status_

**Comment by atungate** [comment]
Looks like it is related to a default on the remotes package (i.e., https://github.com/r-lib/remotes/issues/403) which should be updated in the most recent version. If you reinstall devtools it imports remotes with the version where this is fixed. Let me know what you think about these options (after restarting R, etc.): 

1. Reinstall devtools to see if it works
2. Reinstall remotes 
3. Similar to the linked post, you can change the environment variable before installing (not permanently with this solution): `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")`

Let me know what you think / if you have success with any of these. I think the issue stems from httr being built on a more recent version of R than you are running; it should not be an issue though. However there is an [old] default that stopped installation when this warning popped up / it converted the warning to an error. It should not be an issue in 99% of cases (i.e., why they changed the default back).

**Comment by bonddr** [comment]
> Looks like it is related to a default on the remotes package (i.e., [r-lib/remotes#403](https://github.com/r-lib/remotes/issues/403)) which should be updated in the most recent version. If you reinstall devtools it imports remotes with the version where this is fixed. Let me know what you think about these options (after restarting R, etc.):
> 
> 1. Reinstall devtools to see if it works
> 2. Reinstall remotes
> 3. Similar to the linked post, you can change the environment variable before installing (not permanently with this solution): `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")`
> 
> Let me know what you think / if you have success with any of these. I think the issue stems from httr being built on a more recent version of R than you are running; it should not be an issue though. However there is an [old] default that stopped installation when this warning popped up / it converted the warning to an error. It should not be an issue in 99% of cases (i.e., why they changed the default back).

This worked! Thanks for the helpful explanation.
