### ISSUE TITLE
Scrape error

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#104]
When I run this code:
```
scrape_2021 <- scrape_data(
  src = c("CBS", "ESPN", "FantasyData", "FantasyPros", "FantasySharks", "FFToday",
          "Yahoo", "FantasyFootballNerd", "NFL"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"),
  season = 2021,
  week = 0
)
```

I get
```
Scraping QB projections from 
 https://www.cbssports.com/fantasy/football/stats/QB/2021/season/projections/nonppr 
Error in as_mapper(.f, ...) : object 'xml_remove' not found
```

**Comment by atungate** [comment]
So, I was able to replicate this earlier in the week. When I went to the actual URL it appeared to be in a maintenance window (there was no table there). Can you confirm if this is still an issue for you?

**Comment by TheMathNinja** [comment]
Yes I'm still getting this error today.

**Comment by atungate** [comment]
Hm, I am not able to replicate right now. Currently, scrape_data("CBS", "QB") works as-intended. If it happens again (or now), can you run the following code and let me know if it is missing and/or what it says:

```
test = rvest::read_html("https://www.cbssports.com/fantasy/football/stats/QB/2021/season/projections/nonppr")
test # let me know what this says 

test %>% 
   html_element("table") # let me know what this says as well
```

**Comment by TheMathNinja** [comment]
Ok I think this is resolved. Sorry it was not fixed last time because I was having difficulties downloading the latest package.
