### ISSUE TITLE
Table has inconsistent number of columns

### ISSUE THREAD

**Issue by Tectra** [FantasyFootballAnalytics/ffanalytics#11]
Issue exists for the QB position only. Other positions are collected.

Scraping QB projections from 
 https://www.cbssports.com/fantasy/football/stats/weeklyprojections/QB/1/avg/standard?print_rows=9999 
 Error: Table has inconsistent number of columns. Do you want fill = TRUE? 

Code used
my_scrape <- scrape_data(src = c("CBS"
                                  ,"ESPN"
                                  ,"FantasyPros"
                                  ,"FantasySharks"
                                  ,"FFToday"
                                  ,"FleaFlicker"
                                  ,"NumberFire"
                                  ,"Yahoo"
                                  ,"NFL"
                                  ,"FantasyData"
                                  ,"FantasyFootballNerd"
), 
pos = c("QB", "RB", "WR", "TE","K","DST"),
season = 2018, week = 1)

**Comment by 4pack** [comment]
I'm having this issue as well. Most recent update.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
