### ISSUE TITLE
Scrape issue

### ISSUE THREAD

**Issue by precedex28** [FantasyFootballAnalytics/ffanalytics#111]
I keep getting an error in session(base_link): could not find function "session"

here is the code I am running 
scrape_2021 <- scrape_data(
  src = c("CBS", "ESPN", "FantasyData", "FantasyPros", "FantasySharks", "FFToday",
          "Yahoo", "FantasyFootballNerd", "NFL"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST"),
  season = 2021,
  week = 0
)

**Comment by atungate** [comment]
Sorry about that. `rvest::session()` replaced `rvest::html_session()` once they moved to v1.0.0. So, could you try to update the ffanalytics package and/or the rvest package (make sure to update rvest during the ffanalytics update if it is not >= v1.0.0). I'll push an update to the package later in the week indicating the minimum rvest version.
