### ISSUE TITLE
FantasyPros Weekly Projections on Different URL

### ISSUE THREAD

**Issue by aggieed97** [FantasyFootballAnalytics/ffanalytics#113]
Pulling the Week 1 Projections for 2021, for FantasyPros, it looks like the package is scraping from:
https://www.fantasypros.com/nfl/projections/qb.php

That is the Season Projections for 2021.  

Week 1 is at the following URL, currently:
https://www.fantasypros.com/nfl/rankings/qb.php

At the moment anyway.  Not sure if that changes at some point.

**Comment by atungate** [comment]
Hey @aggieed97, I was working on this some earlier this week. So, I updated the URL; although we don't pull the fantasypros rankings, just the projections. Download the most recent update and please let me know if it does not work for you!

**Comment by aggieed97** [comment]
It works!  Thanks for the fast turn around on that.

**Comment by atungate** [comment]
Sure thing!
