### ISSUE TITLE
scrape data returns 1 week 

### ISSUE THREAD

**Issue by mbjarvis** [FantasyFootballAnalytics/ffanalytics#118]
The `scrape_data` function with the following arguments returns only 1 week of data it appears :

```
my_scrape <- scrape_data(src = c("CBS"), 
                         pos = c("QB", "RB", "WR", "TE"),
                         season = 2020, week = 0)

rb <- my_scrape$RB #to look at it easily 
```

I thought `week = 0` was supposed to return the whole season?

**Comment by mbjarvis** [comment]
The following line in the X script is generating an incorrect link:

```
if(week == 0) {
    scrape_week = "restofseason"
  } else {
    scrape_week = week
  }

.
.
.

l_pos = lapply(pos, function(pos) {
    scrape_link = paste0("https://www.cbssports.com/fantasy/football/stats/", pos, "/",
                         season, "/", scrape_week, "/projections/nonppr/")
```

The resulting link from my above use of the function would return: 

`https://www.cbssports.com/fantasy/football/stats/RB/2020/restofseason/projections/nonppr/`

Navigating to that link you will see that it's actually Week 1 projections for the 2021 season (I think?). In any case, the correct link would read something like: 

```
if(week == 0) {
    scrape_week = "season"
  } else {
    scrape_week = week
  }

.
.
.

l_pos = lapply(pos, function(pos) {
    scrape_link = paste0("https://www.cbssports.com/fantasy/football/stats/", pos, "/",
                         season, "/", scrape_week, "/stats/nonppr/")
```


I haven't tried it out yet but it does just appear to be the erroneous link being generated.

**Comment by atungate** [comment]
Yup, that is where the issue is. At the beginning of this week, CBS started to publish weekly scrapes so I shuffled around the links to grab the current year ROS and weeks for the current year. I had not checked actual stats from past years (I think they only have ~2 years). This weekend I'll test out what you posted above and will push a package update. Thanks for flagging!
