### ISSUE TITLE
Issue while scraping kicker data

### ISSUE THREAD

**Issue by 4pack** [FantasyFootballAnalytics/ffanalytics#12]
When scraping and generating projections for week 1 kicker data, it errors out with the following error:

```
Error in mutate_impl(.data, dots) :
  Evaluation error: object 'fg_0019' not found.
Calls: projections_table ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl
Execution halted
```

This is my scrape/projections generation command:

```
my_scrape <- scrape_data(src = c("ESPN", "Yahoo"), pos = c("QB", "RB", "WR", "TE", "DST", "K"), season = 2018, week = 1)
my_projections <- projections_table(my_scrape)
```

If I remove the **K** position then it correctly generates all the necessary data.

**Comment by MrDAndersen** [comment]
This is fixed now. However, note that ESPN has not yet published weekly data, so the scrape will pull season data for now.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
