### ISSUE TITLE
FFToday scrape is incomplete

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#122]
I noticed today that the FFToday scrape is stopping too early. For example, it's only scraping 2 of 3 projections pages at each IDP position (DL, LB, DB). Could you please update this scrape function to also scrape the 3rd page? Thanks.

Mike

**Comment by atungate** [comment]
Hey Mike, I see your PR but just pushed the fix (https://github.com/FantasyFootballAnalytics/ffanalytics/commit/397d831bdea1b6f5e854259be86d49219f0a3d81). Let us know if you have any more issues!

**Comment by TheMathNinja** [comment]
> Hey Mike, I see your PR but just pushed the fix ([397d831](https://github.com/FantasyFootballAnalytics/ffanalytics/commit/397d831bdea1b6f5e854259be86d49219f0a3d81)). Let us know if you have any more issues!

Unfortunately this seemed to break something. Can you check what broke for me? That's why I submitted the PR.
