### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by stephenhillphd** [FantasyFootballAnalytics/ffanalytics#126]
Running:

```
remotes::install_github("FantasyFootballAnalytics/ffanalytics")
```
Results in the following messages/errors:

Downloading GitHub repo FantasyFootballAnalytics/ffanalytics@HEAD
✔  checking for file 'C:\Users\shill\AppData\Local\Temp\RtmpGkQkBr\remotes24744bb14041\FantasyFootballAnalytics-ffanalytics-322d788/DESCRIPTION'
─  preparing 'ffanalytics': (431ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'ffanalytics_3.0.0.0007.tar.gz'
   
Installing package into ‘C:/Users/shill/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'ffanalytics' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Error : Timeout was reached: [api.myfantasyleague.com] Operation timed out after 10009 milliseconds with 0 out of 0 bytes received
Warning: namespace 'ffanalytics' is not available and has been replaced
by .GlobalEnv when processing object 'projection_sources'
Error : Timeout was reached: [api.myfantasyleague.com] Operation timed out after 10011 milliseconds with 0 out of 0 bytes received
Warning: namespace 'ffanalytics' is not available and has been replaced
by .GlobalEnv when processing object 'projection_sources'
** byte-compile and prepare package for lazy loading
Error : Timeout was reached: [api.myfantasyleague.com] Operation timed out after 10013 milliseconds with 0 out of 0 bytes received
Error: unable to load R code in package 'ffanalytics'
Execution halted
ERROR: lazy loading failed for package 'ffanalytics'
* removing 'C:/Users/shill/AppData/Local/R/win-library/4.2/ffanalytics'
Warning: installation of package ‘C:/Users/shill/AppData/Local/Temp/RtmpGkQkBr/file247466817895/ffanalytics_3.0.0.0007.tar.gz’ had non-zero exit status

**Comment by altwebS** [comment]
Hi @stephenhillphd - I just ran an update and installed the latest changes using devtools without issues.  Might be worth a try.

`devtools::install_github("FantasyFootballAnalytics/ffanalytics") `

When I ran it, I was prompted to update other package, I choose 3:None.  
```
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?
```

**Comment by atungate** [comment]
Hey Stephen,

When installing, the package hits the myfantasyleague API to get the schedule data for the current season. Based on your error, it looks like the API was down for a portion last night (probably due to a lot of people drafting / otherwise hitting the API). Can you let me know if this problem is persisting today?

**Comment by stephenhillphd** [comment]
Thanks. I believe you are correct. The installation was fine this morning and the issue seems to be resolved.

**Comment by atungate** [comment]
Thanks for confirming, Stephen!
