### ISSUE TITLE
Getting error message for Week 1 FFToday scrape

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#127]
Running this:

```
scrape_2022_week1 <- scrape_data(
  src = c("CBS", "ESPN", "FantasyPros", "FantasySharks", "FFToday",
          "Yahoo", "FantasyFootballNerd", "NFL"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"),
  season = 2022,
  week = 1
)
```

Getting this:

```
The FFToday scrape uses a 2 second delay between pages
Scraping QB projections from
 https://www.fftoday.com/rankings/playerwkproj.php?Season=2022&GameWeek=1&PosID=10&LeagueID=1
 Uh oh! Error with the FFToday scrape.
 To get a more specific error message, run:
   ffanalytics:::scrape_fftoday(pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"), season = 2022, week = 1)
```

But FFToday has published their projections and that week 1 URL looks right...

**Comment by TheMathNinja** [comment]
Additionally I get this warning message at the end:
```
Warning message:
Unknown or uninitialised column: `bye`. 
```

**Comment by atungate** [comment]
Hey Mike, looks like FFToday just got their week 1 projections up this morning (we have had our eye on when they would go up in-case we needed to do any patches). We'll get it sorted out later today and push a fix. Thanks!

**Comment by atungate** [comment]
Should be good now--let me know if you have any more issues with it (https://github.com/FantasyFootballAnalytics/ffanalytics/commit/a0385d31a2ff5a0cfc0f77609ab069404cc362f0)
