### ISSUE TITLE
Error in CBS scrape of Kenneth walker in Week 2

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#128]
It's showing:
Player = SEA
Pos = Kenneth Walker III
Team = RB

Not sure if it's CBS-side or something that can be fixed.

**Comment by atungate** [comment]
Looks like a regex issue. I will push a fix after testing a bit more!

**Comment by atungate** [comment]
Hey Mike, https://github.com/FantasyFootballAnalytics/ffanalytics/commit/dd0956f4ca10d6df16a1e51edcf83ed173ba618a should fix it. Let me know if you still have issues!
