### ISSUE TITLE
Getting Actuals Data

### ISSUE THREAD

**Issue by quinnvestments** [FantasyFootballAnalytics/ffanalytics#129]
Is there a function that can be used to pull actuals data (not projections) after a game is complete? 

I'm happy to branch and add it in, but wanted to make sure I'm not overlooking something.

**Comment by atungate** [comment]
Hey quinnvestments, we do not have a function for actuals and we do not plan to add one at the moment. However, I believe nflfastR has what you are looking for (https://github.com/nflverse/nflfastR/). E.g., `calculate_player_stats()` and `calculate_player_stats_def()`. Hope this helps!
