### ISSUE TITLE
projections_table - x must be numeric

### ISSUE THREAD

**Issue by Tectra** [FantasyFootballAnalytics/ffanalytics#13]
issue calculating projections

my_projections <- projections_table(my_scrape)
Error in rowSums(., na.rm = TRUE) : 'x' must be numeric

my_scrape was generated with 
my_scrape <- scrape_data(src = c("CBS"
                                 ,"ESPN"
                                 ,"FantasyPros"
                                 ,"FantasySharks"
                                 ,"FFToday"
                                 ,"FleaFlicker"
                                 ,"NumberFire"
                                 ,"Yahoo"
                                 ,"NFL"
                                 ,"FantasyData"
                                 ,"FantasyFootballNerd"
), 
pos = c("QB", "RB", "WR", "TE","K","DST"),
season = 2018, week = 1)

**Comment by 4pack** [comment]
I'm having this same issue as well.

Error:
```
Error in rowSums(., na.rm = TRUE) : 'x' must be numeric
Calls: projections_table ... _fseq -> freduce -> withVisible -> <Anonymous> -> rowSums
Execution halted
```

Scrape/projection generation line:
```
my_scrape <- scrape_data(src = c("CBS", "ESPN"), pos = c("QB", "RB", "WR", "TE", "DST"), season = 2018, week = 1)
my_projections <- projections_table(my_scrape)
```

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html

**Comment by imaxgillet** [comment]
I am encountering a similar issue on Mac with the given sessionInfo. It appears that the issue arises within the second rowSums in get_stat_cols. The "receiving_tgt" column for the RB data is a <chr> and is causing the issue.
![Screen Shot 2020-08-18 at 3 14 13 PM](https://user-images.githubusercontent.com/13564036/90560941-86ef5600-e165-11ea-939a-0c7ff57bd15a.png)
