### ISSUE TITLE
Missing players with weekly scrape when injury status exists

### ISSUE THREAD

**Issue by altwebS** [FantasyFootballAnalytics/ffanalytics#130]
I have noticed that the weekly scrape output is excluding players that hit IR or are OUT.  Examples are Dak Prescott in week 2 scrapes and Mike Evans in week 3.  Understood that they will have 0 points, I think they used to be returned and now they are missing.  Should they be returned with 0 or excluded?

**Comment by atungate** [comment]
I believe that are you right / they are dropped at the moment but I cannot remember the past implementation. A lot of (maybe all) the scrapes will drop players when the site projected points = 0. I have not thought through it, but would it be helpful to retain those players in the scrape output?

**Comment by altwebS** [comment]
For weekly glance numbers, no, not useful.  My use case is different and was looking week over week and the dropping players were just unexpected from last year.  I have found a way around it for my case and this can be closed.  Thanks for the note back!
