### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mannyrockwell** [FantasyFootballAnalytics/ffanalytics#135]
I've attempted to install the `ffanalytics` package on 3 different machines and all have produced the same error. I'm currently running:

```
 devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics", build_vignettes = TRUE)
```

Downloading GitHub repo FantasyFootballAnalytics/ffanalytics@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Emman\AppData\Local\Temp\RtmpwxtuX1\remotes64c44f3116ac\FantasyFootballAnalytics-ffanalytics-4bb37b4/DESCRIPTION' (435ms)
─  preparing 'ffanalytics':
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package 'ffanalytics' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   Error in FUN(X[[i]], ...) : subscript out of bounds
   Warning: namespace 'ffanalytics' is not available and has been replaced
   by .GlobalEnv when processing object 'projection_sources'
   Error in FUN(X[[i]], ...) : subscript out of bounds
   Warning: namespace 'ffanalytics' is not available and has been replaced
   by .GlobalEnv when processing object 'projection_sources'
   ** byte-compile and prepare package for lazy loading
   Error in FUN(X[[i]], ...) : subscript out of bounds
   Error: unable to load R code in package 'ffanalytics'
   Execution halted
   ERROR: lazy loading failed for package 'ffanalytics'
─  removing 'C:/Users/Emman/AppData/Local/Temp/Rtmp2jL8zH/Rinst60886cfca27/ffanalytics'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'ffanalytics' from GitHub:
  ! System command 'Rcmd.exe' failed

Traceback is as follows:
```
traceback()
```
10: stop(remote_install_error(remotes[[i]], e))
9: value[[3L]](cond)
8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
7: tryCatchList(expr, classes, parentenv, handlers)
6: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
5: install_remotes(remotes, auth_token = auth_token, host = host, 
       dependencies = dependencies, upgrade = upgrade, force = force, 
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
       build_vignettes = build_vignettes, repos = repos, type = type, 
       ...)
4: force(code)
3: withr::with_path(rtools_path(), code)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
           rlang::warn))
       {
           remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
               auth_token = auth_token, host = host)
           install_remotes(remotes, auth_token = auth_token, host = host, 
               dependencies = dependencies, upgrade = upgrade, force = force, 
               quiet = quiet, build = build, build_opts = build_opts, 
               build_manual = build_manual, build_vignettes = build_vignettes, 
               repos = repos, type = type, ...)
       }
   }, required = FALSE)
1: devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics", 
       build_vignettes = TRUE)

**Comment by atungate** [comment]
Hey Manny, missed this but this should be fixed now (https://github.com/FantasyFootballAnalytics/ffanalytics/commit/dff3652669064953d1840d4d85632ed2718ccb35). Apologies! Let me know if you are still having any issues and enjoy the offseason.
