### ISSUE TITLE
impute_via_rates_and_mean

### ISSUE THREAD

**Issue by richard-lacasse** [FantasyFootballAnalytics/ffanalytics#136]
I'm getting this error when I try to run projection_table:

Error in UseMethod("group_by") : 
  no applicable method for 'group_by' applied to an object of class "NULL"

I started debugging and in the impute_via_rates_and_mean function I eventually get to these lines (starting at line 104 in impute_funcs.R):

lapply(names(data_result), function(pos) {
       pos = toupper(pos)
       df = data_result[[tolower(pos)]]

It sets it toupper, then calls it as tolower which makes it NULL.

I'm still fairly inexperienced, so this might not be the problem it looks like to me.

**Comment by acash0902** [comment]
having this same issue, tried changing the data scraping to exclude any NA values but still experiencing this issue.

**Comment by atungate** [comment]
Hey Richard, thanks for flagging. Should be fixed now but let me know if you are still having the issue after updating the package.
