### ISSUE TITLE
No Applicable method for "group_by"

### ISSUE THREAD

**Issue by acash0902** [FantasyFootballAnalytics/ffanalytics#137]
Error in UseMethod("group_by") : 
  no applicable method for 'group_by' applied to an object of class "NULL"

getting this error after scraping the data and then assigning the data to my_projections

**Comment by atungate** [comment]
Hey acash0902, thanks for flagging. Let me know if you are still having the issue after restarting R and downloading the latest version of the package.

**Comment by acash0902** [comment]
@atungate, thank you, it seems to be working now!

**Comment by acash0902** [comment]
Seeing this error now though:

```
Scraping ADP data
Error in UseMethod("html_table") : 
  no applicable method for 'html_table' applied to an object of class "xml_missing"
```

**Comment by atungate** [comment]
Hey @acash0902, I am guessing this was related to pulling yahoo ADP/AAV data but that should be fixed now. I am going to close this but definitely reopen the issue if this is still happening for you.
