### ISSUE TITLE
Adding JSON source - DST scoring

### ISSUE THREAD

**Issue by sansbacon** [FantasyFootballAnalytics/ffanalytics#14]
I'm trying to add a JSON source (profootballfocus)

There is an issue for DST scoring. Instead of projecting the points allowed, the player data will have a key designating a point range. So if the Ravens are projected to give up between 14-20 points, there is a key value pair of "dst_pts_14_20": 1, the Chargers are projected to give up between 21-27 points, so the key value pair is "dst_pts_21_27": 1, etc. 

Is there a way to handle this issue in defining the source? Thanks!

  PFF = list(
    base = "https://www.profootballfocus.com/api/prankster/projections?scoring=preset_ppr"
    get_path = function(week){
      week_no <- ifelse(week == 0, "", as.character(week))
      sprintf("%s&week=%s", base, week_no)
    },
    min_week = 0,
    max_week = 17,
    id_col = "player_id",
    json_elem = list(weekly = "player_projections", season = "player_projections"),
    stat_elem = NULL,
    player_elem = NULL,
    stat_cols = c(pass_att = "pass_att", pass_comp = "pass_comp", pass_yds = "pass_yds",
                  pass_tds = "pass_td", pass_int = "pass_int", 
                  rush_att = "rush_att", rush_yds = "rush_yds", rush_tds = "rush_td", 
                  fumbles_lost = "fumbles_lost", fumbles = "fumbles",
                  rec = "recv_receptions", rec_yds = "recv_yds", rec_tds = "recv_td", 
                  site_pts = "fantasy_points", 
                  dst_sacks = "dst_sacks", dst_int = "dst_int",
                  dst_fum_rec = "dst_fumbles_recovered", dst_fum_force = "dst_fumbles_forced",
                  dst_sacks = "dst_sacks" , dst_td = "dst_td", dst_ret_tds = "dst_return_td",
                  dst_safety = "dst_safeties"
                  ),
    player_cols = c(src_id = "player_id", player = "player_name",  pos = "position")
)

**Comment by MrDAndersen** [comment]
That would require adding some special handling in the `scrape_method` of the `json_source` class where the different variables would be converted to values for `dst_pts_allowed`. You can then use the scoring settings to calculate the points. For example, `dst_pts_14_20 = 1` could be converted to `dst_pts_allowed = 17`. Then in scoring setting would specify an item in the `pts_bracket` element with a theshold of 20,  

The other thing you should be aware of is mapping the `player_id` to MFLs id value for the aggregation and projection calculations to work. You can use the `ffanalytics:::match_players` function to match players by name, position and team and get the MFL ids. For that to work you will need to make sure that the name column is named `player`, the position column is named `pos`, and the team column `team`. The function assumes that positions and team designations are in all caps.

**Comment by sansbacon** [comment]
OK, thanks.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
