### ISSUE TITLE
Add missing MFL ID's

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#140]
I'm running this code:
```
scrape_data(
  src = c("CBS", "ESPN", "FantasyPros", "FantasySharks", "FFToday", "Numberfire",
          "Yahoo", "FantasyFootballNerd", "NFL"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"),
  season = 2023,
  week = 0
)
```

The following ID's are missing from your scrapes:

DL.id: Odafe Oweh: 15378 (he's listed as Jayson Oweh in MFL).
DL.id: John Franklin: 13770 (listed as John Franklin-Myers in MFL).
DB.id: Cobie Durant: 15888 (listed as Decobie Durant in MFL)
DB.id: Joey Porter Jr.: 16240 
QB.id: Mitch Trubisky: 13115 (listed as Mitchell Trubisky in MFL)
RB.id: Jeff Wilson: 14017 (listed as Jeffery Wilson in MFL)
RB.id: Pierre Strong: 15733 (this one is there for FFToday scrape but not others)

These seem like players with common name mapping issues. Perhaps `nflreadr::clean_player_names()` might be of use.

**Comment by atungate** [comment]
Thanks, Mike! We'll have these ID's added in a bit!

**Comment by atungate** [comment]
Hey Mike, I believe these are good-to-go now with the patches to the function we use to pull id's. Let me know if you have issues with anyone else and I will add them manually to our player_id table.
