### ISSUE TITLE
General question about scoring rules

### ISSUE THREAD

**Issue by matthewpaley** [FantasyFootballAnalytics/ffanalytics#142]
I'm helping my dad put a big board together for his league with really non-standard scoring rules. For example:
-  pass_yd_pts = ifelse(pass_yds < 250, 0, 3 points every 50 yards)
-  rec_yd_pts = ifelse(rec_yds < 50, 0, 3 points every 25 yards)
-  rush_yd_pts = ifelse(pass_yds < 30, 0, 3 points every 50 yards)

I'm attempting to do something like this:
```
dad_league$pass$pass_yds <- 0
dad_league$pass$pass_300_yds <- 6
dad_league$pass$pass_350_yds <- 3
dad_league$pass$pass_400_yds <- 3
```
The thresholds wouldn't line up exactly -- if a qb throws for 250 yards, they'd get 0 instead of 3 in this scenario -- but it's better than nothing. My question is, are these settings cumulative? If a qb throws for 350 yards with these settings, will they end up with 3 points, or 9?

Thanks again for all your help!

**Comment by atungate** [comment]
Hey Matthew, great question and cool league settings! They are cumulative so they would end up with 9 in your example. 

For season projections, we do impute these columns based on the `pass_yds` column (assuming the bonus columns are not present in the data). If you wanted to, you could approximate the settings you describe better in a similar fashion. E.g., keep the scoring the same for the pass_yds column `3 points every 25 yards` but adjust the the pass_yds directly based on some historical data. Let me know if you are interested in this kind of approach and I can try to point to in the right direction / see if you are interested. 

As a side-note, I found some old notes that I need to update related-to this code so I'll leave this issue open until I get through the updates.

**Comment by matthewpaley** [comment]
I ended up going with the approach I asked about, mostly due to time constraints. I'd definitely be interested in your suggested approach next year though :)

**Comment by atungate** [comment]
Hey Matthew, as I start to type this out I realize it may be too in-the-weeds. I'll share it anyway and let me know if you have any questions. 

The approach is to adjust the column directly based on historical data (lowering the number of yards based on how often games did not exceed the threshold in the past). We compute bonus stat columns using a similar/rudimentary method (e.g., a +1 point bonus if someone rushes 100+ yards). However, projections don't typically include # of games > 100 yards, so we impute the number of games that may happen based on how often it happened last year & total number of yards.

See here for how we compute the coefficients for those columns (https://github.com/FantasyFootballAnalytics/ffanalytics/blob/master/data-raw/bonus_yds_coefs.R). So in your case, you want to adjust the yards down based on the number of times it did not reach threshold. 

Hope this is helpful / let me know if you have questions
