### ISSUE TITLE
FantasyPros not scraping

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#146]
Currently, FantasyPros should be scrapable, but I'm noticing it's not working correctly. 

```
scrape_data(
  src = c("CBS", "ESPN", "FantasyPros", "FantasySharks", "FFToday", "Numberfire",
          "Yahoo", "FantasyFootballNerd", "NFL"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"),
  season = 2024,
  week = 0
)
```

yields a df without any FantasyPros sources.

**Comment by atungate** [comment]
@TheMathNinja , should be fixed with https://github.com/FantasyFootballAnalytics/ffanalytics/commit/f22557617fa99b25cc689317a76806abcf4ce7ac, let me know if you are still having issues with it.
