### ISSUE TITLE
projections_table - must be numeric

### ISSUE THREAD

**Issue by Tectra** [FantasyFootballAnalytics/ffanalytics#15]
issue calculating projections

my_projections <- projections_table(my_scrape)
Error in rowSums(., na.rm = TRUE) : 'x' must be numeric

my_scrape was generated with
my_scrape <- scrape_data(src = c("CBS"
,"ESPN"
,"FantasyPros"
,"FantasySharks"
,"FFToday"
,"FleaFlicker"
,"NumberFire"
,"Yahoo"
,"NFL"
,"FantasyData"
,"FantasyFootballNerd"
),
pos = c("QB", "RB", "WR", "TE","K","DST"),
season = 2018, week = 1)

looks like CBS works now

**Comment by Tectra** [comment]
I was able to narrow done the culprit to FantasyFootballNerd (i have a subscription).

**Comment by MrDAndersen** [comment]
Did you set your API key for FantasyFootballNerd: `projections_sources$FantasyFootballNerd$api_key <- "api_key"`? If you did then it is probably an issue with the column names  returned from FantasyFootballNerd not matching with the columns specified in `projections_sources$FantasyFootballNerd$stat_cols`.

**Comment by Tectra** [comment]
i did set the key. ill take a look at the stat_cols

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
