### ISSUE TITLE
Two sources coming up blank

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#151]
ffanalytics::scrape_data(
  src = c("CBS", "ESPN", "FantasyPros", "FantasySharks", "FFToday", "Numberfire",
          "FantasyFootballNerd", "NFL", "RTSports", "Walterfootball"),
  pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"),
  season = 2024,
  week = 0
)

yields df's for CBS, ESPN, FantasyPros, FantasySharks, FFToday, NFL.com, RTSports, and WalterFootball. 

However, it does not yield anything for Numberfire or FantasyFootballNerd (gives a warning for FantasyFootballNerd, saying "we're working on it."). Any idea what's not working with Numberfire or FantasyFootballNerd?

**Comment by atungate** [comment]
Hey Mike, we haven't implemented FantasyFootballNerd yet. Last year was a busy one but we are picking back up now. 

For numberfire, I am not experiencing the same issue. If you run just the below function what does it return (or what error does it throw)? Wondering if there is an issue with the scrape or if the site didn't have projections for a little bit.

```r
ffanalytics:::scrape_numberfire()
```

**Comment by TheMathNinja** [comment]
Oh wow, this is dumb. It was because I wasn't capitalizing the F in "fire". Didn't realize this was case-specific. Thanks.
