### ISSUE TITLE
Yahoo AAV is wrong (showing last year's results)

### ISSUE THREAD

**Issue by natp13** [FantasyFootballAnalytics/ffanalytics#152]
The AAV values from the Yahoo source appear to be from last season. It's either an issue with ffanalytics using the wrong endpoint, or there's just a bug in the Yahoo API because pulling the URL directly (https://pub-api-ro.fantasysports.yahoo.com/fantasy/v2/league/423.l.public;out=settings/players;position=ALL;start=0;count=200;sort=rank_season;search=;out=auction_values;out=expert_ranks;expert_ranks.rank_type=projected_season_remaining/draft_analysis;cut_types=diamond;slices=last7days?format=json_f) results in the same incorrect auction values.

**Comment by atungate** [comment]
Good catch--I'll check this out this weekend / see if we can get it resolved. Thanks for opening the issue.

**Comment by atungate** [comment]
@natp13, when you get a sec can you re-install the package and see if https://github.com/FantasyFootballAnalytics/ffanalytics/commit/8f02867dbfb44353ce581023705b05ed005e19c8 fixed it?

**Comment by natp13** [comment]
Yeah looks like it's fixed, thanks!
