### ISSUE TITLE
Why use "week = 0" to reference week 1?

### ISSUE THREAD

**Issue by chris-roerig** [FantasyFootballAnalytics/ffanalytics#16]
```
 my_scrape <- scrape_data(src = c("CBS", "ESPN", "Yahoo"),
                           pos = c("QB", "RB", "WR", "TE", "DST"),
                           season = 2018, week = 0)
```

My understanding is week = 0 is referring to week 1. Is that true? If so, why not use week 1 to make it more clear?

**Comment by MrDAndersen** [comment]
Week = 0 refers to season long data. Week = 1 is week 1.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
