### ISSUE TITLE
Additional projection_table issues

### ISSUE THREAD

**Issue by Tectra** [FantasyFootballAnalytics/ffanalytics#17]
While investigating the source of issue [15](https://github.com/FantasyFootballAnalytics/ffanalytics/issues/15), I did notice a few other issues. I wasn't able to determine if the projections were being included as part of the projections table.

**FantasyPros**: Error in -x : invalid argument to unary operator
**FleaFlicker**: Error: Column `id` not found
**Yahoo**: Error in mutate_impl(.data, dots) : Evaluation error: object 'fg' not found.
**NFL**: Error in .f(.x[[i]], ...) : object 'att' not found
**FantasyData**: Error: `by` can't contain join column `pos`, `data_col` which is missing from LHS
**FantasyFootballNerd**: Error: Column `id` not found

**Comment by MrDAndersen** [comment]
FantasyData is not currently scrapeable due to the way they have changed their site, so I would avoid that source. Were the other issues found by running the sources by themselves?

**Comment by Tectra** [comment]
I forgot about FantasyData (apologies). Yes, I ran each source individually to get the above errors.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
