### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by scottfrechette** [FantasyFootballAnalytics/ffanalytics#2]
When I try to install the package I get the following error: 

`devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics")`

Downloading GitHub repo FantasyFootballAnalytics/ffanalytics@master
from URL https://api.github.com/repos/FantasyFootballAnalytics/ffanalytics/zipball/master
Installing ffanalytics
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/m7hj2/AppData/Local/Temp/RtmpiIwa2K/devtools3d7c1a3c7eba/FantasyFootballAnalytics-ffanalytics-f639f21"  \
  --library="C:/Users/m7hj2/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'ffanalytics' ...
** R
** data
*** moving datasets to lazyload DB
Error in .[[c("fullNflSchedule", "nflSchedule")]] : 
  no such index at level 1

Warning: namespace 'ffanalytics' is not available and has been replaced
by .GlobalEnv when processing object 'projection_sources'
Error in .[[c("fullNflSchedule", "nflSchedule")]] : 
  no such index at level 1

Warning: namespace 'ffanalytics' is not available and has been replaced
by .GlobalEnv when processing object 'projection_sources'
** preparing package for lazy loading
Warning: package 'tidyverse' was built under R version 3.4.4
Warning: package 'ggplot2' was built under R version 3.4.4
Warning: package 'tidyr' was built under R version 3.4.4
Warning: package 'purrr' was built under R version 3.4.4
Warning: package 'dplyr' was built under R version 3.4.4
Warning: package 'rvest' was built under R version 3.4.4
Warning: package 'httr' was built under R version 3.4.4
Warning: package 'readxl' was built under R version 3.4.4
Warning: package 'janitor' was built under R version 3.4.4
Warning: package 'glue' was built under R version 3.4.4
Warning: package 'Hmisc' was built under R version 3.4.4
Warning: package 'Formula' was built under R version 3.4.4
Error in .[[c("fullNflSchedule", "nflSchedule")]] : 
  no such index at level 1

Error : unable to load R code in package 'ffanalytics'
ERROR: lazy loading failed for package 'ffanalytics'
* removing 'C:/Users/m7hj2/Documents/R/win-library/3.4/ffanalytics'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by MrDAndersen** [comment]
@scottfrechette and @sansbacon Could you retry and see if these issues still occur. I have not been able to reproduce.

**Comment by sansbacon** [comment]
I have a global problem with Rcurl timing out.. I don't think it is
specific to your package. It looks like your installation routine fetches
the MFL player list which is why it won't install on my machine.

**Comment by sansbacon** [comment]
I had slow DNS lookup, so default timeout of 10 seconds occurred before the lookup was complete.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
