### ISSUE TITLE
new JSON source already has mfl_player_id

### ISSUE THREAD

**Issue by sansbacon** [FantasyFootballAnalytics/ffanalytics#20]
I am creating a new JSON source. Assume the structure of each object in the list is as follows:
```
{
  "mfl_player_id": 5848, 
  "source_player_id": "tombrady",
  "source_player_name": "Tom Brady",
  "source_team_id": "NE",
  "source_player_position": "QB",
  "stats": { .. stat items ..}
}
 
```
Are the following values correct?

```
id_col = "mfl_player_id",
json_elem = "players",
stat_elem = "stats",
player_elem = NULL,   
player_cols = c(src_id = "source_player_id", player = "source_player_name", 
                team = "source_team_id", pos = "source_player_position")
```

Also, once I add the site description to source_configs.R, what else do I have to do so the source gets scraped when I run scrape_data()?

Thanks for your help!

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
