### ISSUE TITLE
Football Nerds Data Quality issue.

### ISSUE THREAD

**Issue by RandalMorris** [FantasyFootballAnalytics/ffanalytics#21]
Football nerds is pulling old seasons data. Getting RG3 and Kapernick Data

**Comment by MrDAndersen** [comment]
You will need to have an registered API account with Fantasy Football Nerd to get updated data, and then set the `api_key` element on the `projection_sources$FantasyFootballNerd` object to your own API key value. It is currently using "test" for the "api_key" which will return old data.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
