### ISSUE TITLE
problem with knitt

### ISSUE THREAD

**Issue by LordMaplewood** [FantasyFootballAnalytics/ffanalytics#22]
FantasyScrape2 <- scrape_data(src = c("Yahoo"), pos = c("RB", "WR"), season = 2018, week =0)
***
Error in `[.tbl_df`(data = .x, .y[["col"]], .y[["into"]], .y[["regex"]],  : 
  unused argument (convert = TRUE)
Calls: <Anonymous> ... <Anonymous> -> accumulate -> Reduce -> f -> .f -> extract
Execution halted
****
Trouble kniting to html in r studio- any suggestions?

**Comment by MrDAndersen** [comment]
Not able to reproduce this. `scrape_data(src = c("Yahoo"), pos = c("RB", "WR"), season = 2018, week =0)` runs without issues. Not sure what the issue with knitr is.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
