### ISSUE TITLE
Unable to scrape a single week using scrape_source

### ISSUE THREAD

**Issue by jestarr** [FantasyFootballAnalytics/ffanalytics#23]
my_scrape <- scrape_source(src = "ESPN", pos = "QB",season = 2018, week = 1).  I'm getting the error message: 

`Error: $ operator is invalid for atomic vectors`

**Comment by MrDAndersen** [comment]
To do this you will need to use the `projection_sources` object:
```R
scrape_source(src = projection_sources$ESPN, pos = "QB",season = 2018, week = 1)
```

Note that ESPN have taken down their 2018 projections.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
