### ISSUE TITLE
Error with scrape_data

### ISSUE THREAD

**Issue by cranberry314** [FantasyFootballAnalytics/ffanalytics#25]
When I run the standard:

library(ffanalytics)

my_scrape <- scrape_data(src = c("CBS", "ESPN", "Yahoo"),

    * ```
                           pos = c("QB", "RB", "WR", "TE", "DST"),
      ```

    * ```
                           season = 2018, week = 0)
      ```

In RStudio on my newly reinstalled 3.5.1 & 3.4.4 installations I get the following error:

Scraping QB projections from
https://www.cbssports.com/fantasy/football/stats/sortable/points/QB/standard/projections/2018/?print_rows=9999
Error: Column 1 must be named.
Use .name_repair to specify repair.
Call `rlang::last_error()` to see a backtrace
Called from: abort(error_column_must_be_named(bad_name))
Browse[1]>

Any thoughts on what might be going on? This worked last week. I have tried uninstalling/reinstalling R & associated libraries with no success.

**Comment by MrDAndersen** [comment]
I am not able to replicate this. I ran 
```R
my_scrape <- scrape_data(src = c("CBS", "ESPN", "Yahoo"), 
                                 pos = c("QB", "RB", "WR", "TE", "DST"), 
                                 season = 2018, week = 0)
``` 
without issues. I have R 3.5.2 installed and version 1.2.1 of tidyverse

**Comment by cranberry314** [comment]
I'm getting the below when I run it in RStudio, I verified it threw an
object in the plain R GUI as well.

> my_scrape <- scrape_data(src = c("CBS", "ESPN", "Yahoo"),
+                          pos = c("QB", "RB", "WR", "TE", "DST"),
+                          season = 2018, week = 0)
Scraping QB projections from

https://www.cbssports.com/fantasy/football/stats/sortable/points/QB/standard/projections/2018/?print_rows=9999
Error: Column 1 must be named.
Use .name_repair to specify repair.
Call `rlang::last_error()` to see a backtrace
Called from: abort(error_column_must_be_named(bad_name))
Browse[1]> Q
> rlang::last_error()
<error>
message: Column 1 must be named.
Use .name_repair to specify repair.
class:   `rlang_error`
backtrace:
  1. ffanalytics::scrape_data(...)
  2. purrr::map(pos, ~map(projection_sources[src], ~.x))
  9. purrr::transpose(.)
 10. purrr::map(., ~imap(.x, ~scrape_source(.x, season, week, .y)))
 11. ffanalytics:::.f(.x[[i]], ...)
 12. purrr::imap(.x, ~scrape_source(.x, season, week, .y))
 13. purrr::map2(.x, vec_index(.x), .f, ...)
 14. ffanalytics:::.f(.x[[i]], .y[[i]], ...)
 15. ffanalytics::scrape_source(.x, season, week, .y)
 16. src$open_session(season, week, position)$scrape()
 21. self$get_table()
 24. dplyr:::slice.data.frame(data_table, 1)
 26. dplyr::tbl_df(.data)
 27. tibble:::as_tibble.data.frame(data, .name_repair = "check_unique")
 28. tibble:::as_tibble.list(unclass(x), ..., .rows = .rows, .name_repair =
.name_repair)
 29. tibble:::lst_to_tibble(x, .rows, .name_repair, col_lengths(x))
 34. tibble:::set_repaired_names(x, .name_repair)
 35. tibble:::repaired_names(names(x), .name_repair = .name_repair)
  1. tibble:::check_unique(new_name)
Call `rlang::last_trace()` to see the full backtrace
> rlang::last_trace()
     █
  1. └─ffanalytics::scrape_data(...)
  2.   └─`%>%`(...)
  3.     ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  4.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  6.         └─ffanalytics:::`_fseq`(`_lhs`)
  7.           └─magrittr::freduce(value, `_function_list`)
  8.             └─function_list[[i]](value)
  9.               └─purrr::map(., ~imap(.x, ~scrape_source(.x, season,
week, .y)))
 10.                 └─ffanalytics:::.f(.x[[i]], ...)
 11.                   └─purrr::imap(.x, ~scrape_source(.x, season, week,
.y))
 12.                     └─purrr::map2(.x, vec_index(.x), .f, ...)
 13.                       └─ffanalytics:::.f(.x[[i]], .y[[i]], ...)
 14.                         └─ffanalytics::scrape_source(.x, season, week,
.y)
 15.                           └─src$open_session(season, week,
position)$scrape()
 16.                             └─self$get_table()
 17.                               ├─base::suppressWarnings(...)
 18.                               │ └─base::withCallingHandlers(expr,
warning = function(w) invokeRestart("muffleWarning"))
 19.
├─base::mean(is.na(as.numeric(slice(data_table,
1))))
 20.                               ├─dplyr::slice(data_table, 1)
 21.                               └─dplyr:::slice.data.frame(data_table, 1)
 22.
├─base::as.data.frame(slice(tbl_df(.data), ..., .preserve = .preserve))
 23.                                 ├─dplyr::slice(tbl_df(.data), ...,
.preserve = .preserve)
 24.                                 └─dplyr::tbl_df(.data)
 25.                                   ├─tibble::as_tibble(data,
.name_repair = "check_unique")
 26.
└─tibble:::as_tibble.data.frame(data, .name_repair = "check_unique")
 27.
└─tibble:::as_tibble.list(unclass(x), ..., .rows = .rows, .name_repair =
.name_repair)
 28.                                       └─tibble:::lst_to_tibble(x,
.rows, .name_repair, col_lengths(x))
 29.
└─tibble:::set_repaired_names(x, .name_repair)
 30.                                           ├─rlang::set_names(x,
repaired_names(names(x), .name_repair = .name_repair))
 31.                                           │
└─rlang:::set_names_impl(x, x, nm, ...)
 32.                                           │   └─rlang::is_function(nm)
 33.                                           │     └─rlang::is_closure(x)
 34.
└─tibble:::repaired_names(names(x), .name_repair = .name_repair)
 35.
└─tibble:::check_unique(new_name)

**Comment by MrDAndersen** [comment]
Have you tried re-installing the package?

**Comment by cranberry314** [comment]
Yep, I am so embarrassed about this that I even tried reinstalling R before
pinging the thread. I just reran devtools with force = TRUE, it threw this
message during install and failed when I hit run.

> devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics",
build_vignettes = TRUE, force = TRUE)
Downloading GitHub repo FantasyFootballAnalytics/ffanalytics@master
✔  checking for file
‘/private/var/folders/21/gvg2jg0n4rq2w721wty31c200000gn/T/RtmpXmclOs/remotes178cc4bed780f/FantasyFootballAnalytics-ffanalytics-949ed52/DESCRIPTION’
...
─  preparing ‘ffanalytics’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘ffanalytics_2.0.0.1003.tar.gz’

* installing *source* package ‘ffanalytics’ ...
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to '=='
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ffanalytics)

**Comment by cranberry314** [comment]
It had been running without incident on my system for the past several
months until it suddenly started throwing errors. So I uninstalled R,
reinstalled R, and reinstalled all of the libraries however it was still
failing.

**Comment by cranberry314** [comment]
Any thoughts?

**Comment by cranberry314** [comment]
I deleted the RStudio defaults and tried again, this is what I got for the traceback.

> my_scrape <- scrape_data(src = c("Yahoo"), 
+                          pos = c("QB", "RB", "WR", "TE", "DST"),
+                          season = 2018, week = 0)
Scraping QB projections from 
 https://football.fantasysports.yahoo.com/f1/48938/players?sort=PTS&sdir=1&status=A&pos=QB&stat1=S_PS_2018&jsenabled=1&count=0 
 Hide Traceback
 
 Rerun with Debug
 Error: Columns 1, 2, 3, 4, 5, … (and 2 more) must be named.
Use .name_repair to specify repair.
Call `rlang::last_error()` to see a backtrace 
37.stop(cnd) 
36.abort(error_column_must_be_named(bad_name)) 
35.check_unique(new_name) 
34.repaired_names(names(x), .name_repair = .name_repair) 
33.is_closure(x) 
32.is_function(nm) 
31.set_names_impl(x, x, nm, ...) 
30.set_names(x, repaired_names(names(x), .name_repair = .name_repair)) 
29.set_repaired_names(x, .name_repair) 
28.lst_to_tibble(x, .rows, .name_repair, col_lengths(x)) 
27.as_tibble.list(unclass(x), ..., .rows = .rows, .name_repair = .name_repair) 
26.as_tibble.data.frame(data, .name_repair = "check_unique") 
25.as_tibble(data, .name_repair = "check_unique") 
24.tbl_df(.data) 
23.slice(tbl_df(.data), ..., .preserve = .preserve) 
22.as.data.frame(slice(tbl_df(.data), ..., .preserve = .preserve)) 
21.slice.data.frame(data_table, 1) 
20.slice(data_table, 1) 
19.mean(is.na(as.numeric(slice(data_table, 1)))) 
18.withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) 
17.suppressWarnings(mean(is.na(as.numeric(slice(data_table, 1)))) > 
    0.9) at source_classes.R#341
16.self$get_table() at source_classes.R#385
15.src$open_session(season, week, position)$scrape() 
14.scrape_source(.x, season, week, .y) 
13..f(.x[[i]], .y[[i]], ...) 
12.map2(.x, vec_index(.x), .f, ...) 
11.imap(.x, ~scrape_source(.x, season, week, .y)) 
10..f(.x[[i]], ...) 
9.map(., ~imap(.x, ~scrape_source(.x, season, week, .y))) 
8.function_list[[i]](value) 
7.freduce(value, `_function_list`) 
6.`_fseq`(`_lhs`) 
5.eval(quote(`_fseq`(`_lhs`)), env, env) 
4.eval(quote(`_fseq`(`_lhs`)), env, env) 
3.withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
2.map(pos, ~map(projection_sources[src], ~.x)) %>% transpose() %>% 
    map(~imap(.x, ~scrape_source(.x, season, week, .y))) %>% 
    transpose() %>% map(discard, is.null) %>% map(bind_rows, 
    .id = "data_src") 
1.scrape_data(src = c("Yahoo"), pos = c("QB", "RB", "WR", "TE", 
    "DST"), season = 2018, week = 0)

**Comment by subtlecalculator** [comment]
I'm having the same issue as @cranberry314. Has anyone learned anything new on how to address the problem? I also have warnings that the tables could not be found on the respective urls.

**Comment by cranberry314** [comment]
Support for phantomjs ended recently so I figured it might have been the
issue, though I am not sure. Since I couldn’t get ffanalytics going I
decided to pursue another route.

**Comment by subtlecalculator** [comment]
I'm thinking this is more specific to our setup. It doesn't seem that everyone else has this issue.

**Comment by subtlecalculator** [comment]
@MrDAndersen maybe this will help shed light on the issue. After running devtools::install_github("FantasyFootballAnalytics/ffanalytics") I get the following: 

* installing *source* package 'ffanalytics' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to '==' 
** help
*** installing help indices
  converting help for package 'ffanalytics'
    finding HTML links ... done
    Impute                                  html  
    add_aav                                 html  
    add_adp                                 html  
    add_ecr                                 html  
    add_player_info                         html  
    add_risk                                html  
    add_vor                                 html  
    aggregate_stats                         html  
    calculate_risk                          html  
    cbs_draft                               html  
    cohens_d                                html  
    confidence_interval                     html  
    custom_scoring                          html  
    default_baseline                        html  
    default_threshold                       html  
    default_weights                         html  
    espn_draft                              html  
    ffc_draft                               html  
    get_adp                                 html  
    html_source                             html  
    finding level-2 HTML links ... done

    json_source                             html  
    nfl_draft                               html  
    points_sd                               html  
    projected_points                        html  
    projection_source                       html  
Rd warning: C:/Users/afqui/AppData/Local/Temp/RtmpwtuRx9/R.INSTALL16784cfe61b7/ffanalytics/man/projection_source.Rd:63: missing link 'player_ids'
    projections_table                       html  
    rts_draft                               html  
    scoring                                 html  
    scrape_data                             html  
    scrape_source                           html  
    set_tiers                               html  
    set_vor                                 html  
    source_points                           html  
    stats_by_category                       html  
    weighted.sd                             html  
    wilcox.loc                              html  
    xlsx_source                             html  
    yahoo_draft                             html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ffanalytics)

I see there is an Rd warning that identifies a missing link 'player_ids'.
This article may shed some light on the nature of the issue https://stackoverflow.com/questions/48430093/how-do-i-resolve-rd-warning-missing-file-link-when-building-packages-in-rstudi

But i'm not sure how to act on that information. 
Any thoughts?

**Comment by cranberry314** [comment]
@subtlecalculator were you able to figure out the issue?

**Comment by subtlecalculator** [comment]
No @cranberry314  I couldn't figure it out. 
I fired up an EC2 instance on Linux 2 with R & Rstudio set up and tried redoing the instructions that @MrDAndersen  has on his website but I got the exact same issue. No clue how to fix it. I'm going to try to use some other method to collect the data. Not sure how long that will take me to put together.

**Comment by gheemony** [comment]
Having the same problem. Is this package supported any more?

**Comment by MrDAndersen** [comment]
Have you installed the new version of the package that is updated for the 2019 season (current version is 2.0.1.0002). Running scrapes for previous seasons and weeks is not recommended with this package as most sites don't keep historical records of projections.  When submitting issues please submit a code snippet and steps to reproduce the issue.

**Comment by Jeffery-777** [comment]
Oh man. That's disappointing. I wanted to crunch some numbers on
projections across years to nerd out and look for patterns.

**Comment by gheemony** [comment]
The issue was a conflict between the ffanalytics package and the nflscrapr package. scrape_data works if ffanalytics is loaded after nflscrapr (and trumps nflscrapr). I haven't checked if nflscrapr works in this manner.

Thanks for building and supporting this package!

**Comment by isaactpetersen** [comment]
@Jeffery-777 For info how to get historical projections, see here: https://fantasyfootballanalytics.net/about-the-site/faq#historicalProjections

**Comment by gheemony** [comment]
I am a personal, not commercial, user that can't afford $1,000+ for the API. Would you recommend that the best way to access and work with historical projections is to subscribe, download CSVs, and then load into R? Thanks.

parag.gheewala@gmail.com | 425.503.3039 | LinkedIn

**Comment by isaactpetersen** [comment]
Yes, I'd recommend using the app with FFA Insider to access the historical projections.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
