### ISSUE TITLE
Trying to load 2019 ESPN proj

### ISSUE THREAD

**Issue by mjmertz08** [FantasyFootballAnalytics/ffanalytics#26]
Getting the below error...

myScrapeData <- runScrape(week = 0, season = 2019, analysts = c(4), positions = c("QB"), fbgUser = NULL, fbgPwd = NULL)
Retrieving player data 
Operation in progressfailed to load external entity "http://football.myfantasyleague.com/2019/export?TYPE=players&L=&W=0&JSON=0&DETAILS=1"
Error: 1: Operation in progress2: failed to load external entity "http://football.myfantasyleague.com/2019/export?TYPE=players&L=&W=0&JSON=0&DETAILS=1"

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
