### ISSUE TITLE
Old Seasons?

### ISSUE THREAD

**Issue by Jeffery-777** [FantasyFootballAnalytics/ffanalytics#27]
I successfully followed tutorials to get me the 2018 data but I figured if I scrape and change the season to past seasons (2017, 2016, etc.) it would scrape those seasons but as I found out it just rescrapes 2018 instead. 

How do we go about getting prior seasons data?

**Comment by isaactpetersen** [comment]
https://fantasyfootballanalytics.net/about-the-site/faq#historicalProjections

**Comment by Jeffery-777** [comment]
Hi there, thanks for the link. I was interested in subscribing but the link
to  https://apps.fantasyfootballanalytics.net/ isn't working on two devices
I tried. Is it up? I can't figure out how to subscribe elsewhere on the
site.

Thanks!

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html

**Comment by Jeffery-777** [comment]
How do I cancel my monthly subscription?

**Comment by isaactpetersen** [comment]
> How do I cancel my monthly subscription?

Please see the FAQ: https://fantasyfootballanalytics.net/about-the-site/faq#ffaInsider
