### ISSUE TITLE
Missing Yards gained data for QB's

### ISSUE THREAD

**Issue by Jeffery-777** [FantasyFootballAnalytics/ffanalytics#28]
I'm noticing yards_gained and other yards associated columns are not logged for the following quarterbacks and games:

- Ben Roethlisberger for game_id: 2013112401
- Brandon Weeden for game_ID: 2013112401
- Chris Henne, game_ID: 2013120101
- Jason Cambell, game_id: 2013112401

Found this in a dplyr summarize call on QBs so possible it's missing for receivers as well.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
