### ISSUE TITLE
Where is the API key located?

### ISSUE THREAD

**Issue by Jeffery-777** [FantasyFootballAnalytics/ffanalytics#29]
I just subscribed and read the article stating my API key would be in the "My Account" modal but it is not there. Please advise. thank you!

**Comment by isaactpetersen** [comment]
You are subscribed to FFA Insider, not the API. To subscribe to the API, sign up for the Basic API or Premier API package, as described here:
https://fantasyfootballanalytics.net/2018/06/fantasy-football-analytics-api.html

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
