### ISSUE TITLE
Source data throwing errors unless sources are removed

### ISSUE THREAD

**Issue by kobybeast** [FantasyFootballAnalytics/ffanalytics#3]
R 3.5.1
All dependency packages updated this AM

During scrape using all sources:
_my_scrape <- scrape_data(src = c("CBS", "ESPN", "FantasyData", "FantasyPros",
  "FantasySharks", "FFToday", "FleaFlicker", "NumberFire", "Yahoo",
  "FantasyFootballNerd", "NFL", "RTSports", "Walterfootball"), pos = c("QB",
  "RB", "WR", "TE", "K", "DST"), season = 2018, week = 0)_

I encountered the following error:
**Error in bind_rows_(x, .id) : 
  Column `rec` can't be converted from numeric to character**
After trial and error I eventually removed FantasyData and FantasyFootballNerd from the source list in order to complete the scrape successfully.

Next, after running the projections_table function I encountered the following error:
**Error in right_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
  std::bad_alloc**

After more trial and error, I eventually removed FantasyPros as well.

In the end, the final set of sources that worked from start to finish were:

my_scrape <- scrape_data(c("CBS", "ESPN",
                           "FantasySharks", "FFToday", "FleaFlicker", "NumberFire","Yahoo",
                           "NFL", "RTSports", "Walterfootball"), 
                         pos = c("QB", "RB", "WR", "TE", "K","DST"),
                         season = 2018, week = 0)

**Comment by MrDAndersen** [comment]
This should be fixed now. Note that FantasyData is not working as they have changed their site structure and we haven't been able to figure a way to successfully scrape the data from the site.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
