### ISSUE TITLE
troubling loading projections after scraping

### ISSUE THREAD

**Issue by nicolegottretm** [FantasyFootballAnalytics/ffanalytics#32]
hi, using the tool for the first time (and very excited!). I was following the initial instructions and was able to create a scrape using the tutorial's command:
my_scrape <- scrape_data(src = c("CBS", "ESPN", "Yahoo"), 
                          pos = c("QB", "RB", "WR", "TE", "DST"),
                          season = 2018, week = 0)

however, when I try to see the projections using:
my_projections <-  projections_table(my_scrape)
 
I am getting the below errors:
Warning messages:
1: Unknown columns: `id`, `data_src` 
2: Unknown columns: `id`, `data_src` 
3: Unknown columns: `id`, `data_src` 
4: Unknown columns: `id`, `data_src` 
5: Unknown columns: `id`, `data_src` 
6: Unknown columns: `id`, `data_src` 
7: Unknown columns: `id`, `data_src` 
8: Unknown columns: `id`, `data_src` 

any tips? Thanks!

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
