### ISSUE TITLE
NumberFire - Rookies

### ISSUE THREAD

**Issue by gheemony** [FantasyFootballAnalytics/ffanalytics#33]
When scraping NumberFire projections for Week 1, the (MFL) id for rookie players at all positions (Kyler Murray, Miles Sanders, etc.) are not added. I haven't been able to identify the script where id is appended to the scraped projections, so I am unable to identify the problem or to fix it. I am relatively new to R, so sorry if there is an obvious solution. 

(Murray is nF's number 1 QB for week 1, so important to get this fixed.)

**Comment by RandalMorris** [comment]
I am seeing 14056 for Kyler Murray in the player table

**Comment by gheemony** [comment]
Same, but it is NA in the projection table. I guess I need to override the NA in id for Kyler and similar players by matching/joining the projection table and player table by name. That requires joining first_name and last-name (I am not sure why MFL name was split in the first place). This is one thing that I think is easier in Excel (vlookup).

**Comment by MrDAndersen** [comment]
Can you provide the code you are running? I am not able to replicate the issue. The id mapping takes place via the `ffanlytics:::player_ids` table what has a both NumberFire and MFL ids for Kyler Murray.

**Comment by gheemony** [comment]
# Load Libraries ----
library(ffanalytics)

# Set scoring parameters: my_scoring ----
my_scoring <- list(
  pass = list(
    pass_att = 0, pass_comp = 0, pass_inc = 0, pass_yds = 0.04, pass_tds = 4,
    pass_int = -3, pass_40_yds = 0,  pass_300_yds = 0, pass_350_yds = 0,
    pass_400_yds = 0
  ),
  rush = list(
    all_pos = TRUE,
    rush_yds = 0.1,  rush_att = 0, rush_40_yds = 0, rush_tds = 6,
    rush_100_yds = 0, rush_150_yds = 0, rush_200_yds = 0),
  rec = list(
    all_pos = TRUE,
    rec = 0, rec_yds = 0.1, rec_tds = 6, rec_40_yds = 0, rec_100_yds = 0,
    rec_150_yds = 0, rec_200_yds = 0
  ),
  misc = list(
    all_pos = TRUE,
    fumbles_lost = -3, fumbles_total = 0,
    sacks = 0, two_pts = 2
  ),
  kick = list(
    xp = 1.0, fg_0019 = 3.0,  fg_2029 = 3.0, fg_3039 = 3.0, fg_4049 = 4.0,
    fg_50 = 5.0,  fg_miss = 0.0
  ),
  ret = list(
    all_pos = TRUE,
    return_tds = 6, return_yds = 0
  ),
  idp = list(
    all_pos = TRUE,
    idp_solo = 1, idp_asst = 0.5, idp_sack = 2, idp_int = 3,  idp_fum_force = 3,
    idp_fum_rec = 2,  idp_pd = 1, idp_td = 6,  idp_safety = 2
  ),
  dst = list(
    dst_fum_rec = 2,  dst_int = 2, dst_safety = 2, dst_sacks = 1, dst_td = 6,
    dst_blk = 1.5, dst_ret_yds = 0, dst_pts_allowed = 0
  ),
  pts_bracket = list(
    list(threshold = 0, points = 10),
    list(threshold = 6, points = 7),
    list(threshold = 20, points = 4),
    list(threshold = 34, points = 0),
    list(threshold = 99, points = -4)
  )
)

# Scrape Raw Projection Data (set week): my_scrape ----
my_scrape <- scrape_data(src = c("CBS", "ESPN", "FantasyData", "FantasyPros", 
                                 "FantasySharks", "FFToday", "FleaFlicker", 
                                 "NumberFire", "Yahoo", "FantasyFootballNerd",
                                 "NFL", "RTSports","Walterfootball"), 
                         pos = c("QB", "RB", "WR", "TE", "DST"),
                         season = 2019, week = 1)

# Convert raw projections to fantasy scoring: my_projections ----
my_projections <- projections_table(my_scrape, scoring_rules = my_scoring)

# Add player info to my_projections ----
my_projections <- my_projections %>% 
  add_player_info()

# Add ECR, Risk, ADP, and AAV ----
my_projections <- my_projections %>% 
  add_ecr() %>% 
  add_risk() %>%
  add_adp() %>% 
  add_aav()

**Comment by RandalMorris** [comment]
DataQB <- rbind(my_scrape[["QB"]]) 

If you run that does if have his ID for the sources? 


DataQB <- rbind(my_scrape[["QB"]]) %>% add_player_info()

Then with this does it?

I could be because not every source has a weekly projections. Try doing just 1 known source that has week 1 data.

**Comment by gheemony** [comment]
Thanks for the suggestions. I tried all of them and none of them worked. For some reason, rookie ids are not being matched for numberFire, which has [week 1 projections](http://www.numberfire.com/nfl/fantasy/fantasy-football-projections/rb).

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
