### ISSUE TITLE
'dst_ret_td' vs 'dst_ret_tds'

### ISSUE THREAD

**Issue by gheemony** [FantasyFootballAnalytics/ffanalytics#34]
All/most sources scrape defensive return touchdowns as "dst_ret_td" (singluar), except Yahoo is scraped as "dst_ret_tds" (plural) and results in two separate columns. I manually solved this by summing the two columns (treating NAs as 0), but it's probably worth fixing this in the base code.

**Comment by RandalMorris** [comment]
My yahoo scrape for DST doesn't anything lol.

**Comment by gheemony** [comment]
You can't replicate with my code?

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
