### ISSUE TITLE
ECR non functioning

### ISSUE THREAD

**Issue by RandalMorris** [FantasyFootballAnalytics/ffanalytics#35]
add_ecr() broke for me...dont know why, but it never returned data to begin with ayway. Now i get a error on the add_column() Function when it tries to import the fp_ids. fp_ids is not getting the ID from the scrape

I fixed it in my repo, but that didn't populate the sd_ecr..etc fields. I changed it to use the Full Name because the ID was not matching and this is how i add ECR.

my_projections <- projections_table(my_scrape, scoring_rules)
my_projections <- my_projections %>% add_player_info()
my_projections$first_name <- paste(my_projections$first_name, my_projections$last_name)
names(my_projections)[2] <- c("name")
my_projections = subset(my_projections, select = -c(last_name))
my_projections <- my_projections %>% add_ecr() %>% add_risk()

**Comment by MrDAndersen** [comment]
This should be fixed now

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
