### ISSUE TITLE
No id for Yahoo DST when scraping week 1

### ISSUE THREAD

**Issue by gheemony** [FantasyFootballAnalytics/ffanalytics#36]
scrape_data does not provide id for DSTs when scraping Yahoo for week 1

```
my_scrape <- scrape_data(src = c("Yahoo"), 
                         pos = c("QB", "RB", "WR", "TE", "DST"),
                         season = 2019, week = 1)
```

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
