### ISSUE TITLE
Add ADP isnt working

### ISSUE THREAD

**Issue by gregalytics** [FantasyFootballAnalytics/ffanalytics#38]
my_projections %>% add_ecr() %>% add_risk() %>%
+   add_adp() 

Error: `nm` must be `NULL` or a character vector the same length as `x`

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html

**Comment by imaxgillet** [comment]
Had the same issue as @RandalMorris and found the same cause: the rename_at(). 

Testing it locally, changing "rename_at(length(.), ~ function(x)return("adp"))" to "     rename_at(length(.), function(x){return("adp")})" worked. The same idea applies to changing "rename_at(length(.), ~ function(x)return("aav"))" to "rename_at(length(.), function(x){return("aav")})"

**Comment by isaactpetersen** [comment]
Good catch! We're hard at work on other things at the moment, but feel free to make a pull request for these fixes--thanks!
