### ISSUE TITLE
Cannot Scrape 2019 Wk 1 Data

### ISSUE THREAD

**Issue by heyitsfred** [FantasyFootballAnalytics/ffanalytics#39]
Run into the following error when trying to load week one data for 2019 season.

Error: Column `fg` can't be converted from numeric to character
In addition: There were 50 or more warnings (use warnings() to see the first 50)

script:
my_scrape <- scrape_data(pos=c("QB","RB","WR","TE","DST", "K"),season = 2019, week =1)

Sorry if this is trial - new to this whole thing.

**Comment by heyitsfred** [comment]
Trying limiting sources.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
