### ISSUE TITLE
Ceiling and Floor estimates are way off for QB and WR

### ISSUE THREAD

**Issue by day536** [FantasyFootballAnalytics/ffanalytics#40]
Scraped fresh data today with scrape_data() and calculated new projections - data was very volatile for QB and WR ceiling and floor, way out of the ordinary. Was seen especially in QB's, and WR's had spreads (Floor/Ceiling) about 4 times larger than those of RB's, which was far different from calculations I have done in the past week. Confirmed the issue by using an old scrape from last week and data was much more normal when calculating projections. Also tried changing around the rules for the fresh scrape with PPR, 0.5 PPR, and standard scoring, and the projections were still very out of the ordinary for QB and WR.

**Comment by day536** [comment]
These projections are for the entire season by the way (week = 0), not a specific week.

**Comment by RandalMorris** [comment]
Certain sites don't have week 1 data yet too 

FFTODAY usually Wednesday and I'm having sissi's scraping FantasySharks atm but the site is up.

CBS just turned on their weekly projections...beware they are wonky...Golden Tate is suspended but they have him with like 14 pts lol

**Comment by day536** [comment]
Ok so just to clarify - some sites do not have full-season projections anymore? I figured that could be the issue, but is there a scrape available with updated full-season projections for all sites? Or if I want full-season, do I just need to exclude CBS? The reason I ask is because I have a draft tomorrow and wanted to get an updated scrape of projections. Can I not scrape with week = 0 anymore?

**Comment by RandalMorris** [comment]
I didn't realize you commented on your own. Season data is fine still.

Honestly its probably bad data from a site...I'm going go say FantasySharks because I had this issue and I think it was them. Week 1 data is not working for them now too.

Either scrape a site 1 at a time or run this after you scrape and find a player you know has a wide gap

DataQB <- rbind(my_scrape[["QB"]]) %>% add_player_info()

**Comment by day536** [comment]
Removing CBS did the trick - it was including projections for week 1 instead of full-season projections, creating a huge outlier for all those players lol. Thank you very much for the tip!

**Comment by RandalMorris** [comment]
Yeah I think they used the same site for both season and weekly because it was showing season data in week 1 yesterday even though the links are different. Today it shows week 1.

Usually when something goes off randomly for no reason either the data is bad and/or the site changed their code.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
