### ISSUE TITLE
ESPN projections

### ISSUE THREAD

**Issue by sansbacon** [FantasyFootballAnalytics/ffanalytics#42]
If you take a look at https://github.com/sansbacon/nfl/blob/master/nfl/espn_api.py it shows in python how to scrape the ESPN API for season-long and weekly projections. The easiest way is to scrape team-by-team because you don't have to deal with any offsets (no team has more than 50 players with fantasy projections). I'm not sure how to handle cookies and other parameters in R, but it shouldn't be too hard for an experienced programmer to adapt it for this library.

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
