### ISSUE TITLE
Weekly scrape failure

### ISSUE THREAD

**Issue by johnchoiniere** [FantasyFootballAnalytics/ffanalytics#5]
Package installed fine, using R 3.5.1 within Rstudio. 

The `scrape_data` function works great when setting week=0,  but fails when attempting a specific week.

`> chk <- scrape_data(src = c("CBS","ESPN"), pos = c('QB','RB'), season = 2018, week = 0)
Scraping QB projections from 
 https://www.cbssports.com/fantasy/football/stats/weeklyprojections/QB/season/avg/standard?print_rows=9999 
Scraping RB projections from 
 https://www.cbssports.com/fantasy/football/stats/weeklyprojections/RB/season/avg/standard?print_rows=9999 
Scraping QB projections from 
 http://games.espn.com/ffl/tools/projections?slotCategoryId=0&seasonTotals=true&seasonId=2018&startIndex=0 
Scraping RB projections from 
 http://games.espn.com/ffl/tools/projections?slotCategoryId=2&seasonTotals=true&seasonId=2018&startIndex=0 `

`> chk <- scrape_data(src = c("CBS","ESPN"), pos = c('QB','RB'), season = 2018, week = 1)
Scraping QB projections from 
 https://www.cbssports.com/fantasy/football/stats/weeklyprojections/QB/1/avg/standard?print_rows=9999 
 Hide Traceback
 
 Rerun with Debug
 Error: Table has inconsistent number of columns. Do you want fill = TRUE? 
27. stop("Table has inconsistent number of columns. ", "Do you want fill = TRUE?", 
    call. = FALSE) 
26. html_table.xml_node(., header = TRUE) 
25. html_table(., header = TRUE) 
24. function_list[[k]](value) 
23. withVisible(function_list[[k]](value)) 
22. freduce(value, `_function_list`) 
21. `_fseq`(`_lhs`) 
20. eval(quote(`_fseq`(`_lhs`)), env, env) 
19. eval(quote(`_fseq`(`_lhs`)), env, env) 
18. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
17. data_page %>% html_node(table_css) %>% html_table(header = TRUE) at source_classes.R#325
16. self$get_table() at source_classes.R#383
15. src$open_session(season, week, position)$scrape() 
14. scrape_source(.x, season, week, .y) 
13. .f(.x[[i]], .y[[i]], ...) 
12. map2(.x, vec_index(.x), .f, ...) 
11. imap(.x, ~scrape_source(.x, season, week, .y)) 
10. f(.x[[i]], ...) 
9. map(., ~imap(.x, ~scrape_source(.x, season, week, .y))) 
8. function_list[[i]](value) 
7. freduce(value, `_function_list`) 
6. `_fseq`(`_lhs`) 
5. eval(quote(`_fseq`(`_lhs`)), env, env) 
4. eval(quote(`_fseq`(`_lhs`)), env, env) 
3. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
2. map(pos, ~map(projection_sources[src], ~.x)) %>% transpose() %>% 
    map(~imap(.x, ~scrape_source(.x, season, week, .y))) %>% 
    transpose() %>% map(discard, is.null) %>% map(bind_rows, 
    .id = "data_src") 
1. scrape_data(src = c("CBS", "ESPN"), pos = c("QB", "RB"), season = 2018, 
    week = 1)`

Please let me know if there's any other information I can provide.

**Comment by MrDAndersen** [comment]
ESPN and CBS have not published week 1 data yet, so data scrape is not successful

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
