### ISSUE TITLE
No player_table to add player data

### ISSUE THREAD

**Issue by packstician** [FantasyFootballAnalytics/ffanalytics#66]
After successfully scraping for week 1 in R, and successfully turning the scrape into projections. I have receive the error 

"Error in select(player_table, id, first_name, last_name, team, position,  : 
  object 'player_table' not found"

After reading the sight this table is supposed to be loaded from MLF on package load. This is not happening for me. I have tried reinstalling the package and nothing seems to work.

**Comment by BeardedJayhawk** [comment]
I ran into this after clearing the workspace. the player table should load when you load up the library, but sometimes it doesn't happen. you can restart your session, detach the package then attach it again. 

I have used this to clear the workspace while leaving the player_table in place:

`rm(list=setdiff(ls(), "player_table"))`

or, this is the function called when you load ffanalytics:

```
player_table <<- httr::GET("https://api.myfantasyleague.com/2020/export?TYPE=players&L=&APIKEY=&DETAILS=1&SINCE=&PLAYERS=&JSON=1") %>%
    httr::content() %>% `[[`("players") %>% `[[`("player") %>%
    purrr::map(tibble::as_tibble) %>%
    dplyr::bind_rows() %>%
    dplyr::filter(position %in% c("QB", "RB", "WR", "TE", "PK", "Def", "DE", "DT", "LB", "CB", "S")) %>%
    dplyr::select(id, name, position, team, weight, draft_year, draft_team, draft_round, draft_pick, birthdate) %>%
    tidyr::extract(name, c("last_name", "first_name"), "(.+),\\s(.+)") %>%
    dplyr::mutate(birthdate = as.Date(as.POSIXct(as.numeric(birthdate), origin = "1970-01-01")),
                  position = dplyr::recode(position, Def = "DST", PK = "K"),
                  age = as.integer(lubridate::year(Sys.time()) - lubridate::year(birthdate)),
                  exp = 2020 - as.integer(draft_year))
```

**Comment by packstician** [comment]
Awesome, thanks @BeardedJayhawk. I haven't gotten it to load when I call the package but used this function instead to get the player table and use it. I will try the other options though. Thanks again!
