### ISSUE TITLE
ADP - option for league scoring

### ISSUE THREAD

**Issue by sansbacon** [FantasyFootballAnalytics/ffanalytics#7]
For the add_adp function, there should be an option for PPR, half PPR, or standard.
The fantasypros URLs are as follows:

STD: https://www.fantasypros.com/nfl/adp/overall.php
HPPR: https://www.fantasypros.com/nfl/adp/half-point-ppr-overall.php
PPR: https://www.fantasypros.com/nfl/adp/ppr-overall.php

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
