### ISSUE TITLE
No Rookies in My_Player_Pool

### ISSUE THREAD

**Issue by Rosey1990** [FantasyFootballAnalytics/ffanalytics#71]
Title says it all.  I don't see Rookies showing up in the My_Player_Pool df when the package is loaded.  Similarly the "Las Vegas Raiders" are still listed as the "Oakland Raiders"

**Comment by atungate** [comment]
Hey Rosey, just FYI, rookies should already be in there for this year but please pos an issue if you notice that anybody is missing.
