### ISSUE TITLE
source_configs.R issues

### ISSUE THREAD

**Issue by phreakin** [FantasyFootballAnalytics/ffanalytics#72]
If anyone has fixed the source_configs.R issue, please post them. So far here's the issues i've found.

ESPN - Wrong URL and scrape info. Old url doesn't work, the new one is https://fantasy.espn.com/football/players/projections
Yahoo - MULTIPLE issues along the lines of ESPN
NFL - Same as above.

**Comment by atungate** [comment]
Hey phreakin, I believe yahoo uses fantasypros projections now (please correct me if I am wrong); NFL is working now, and we'll have ESPN up and running again soon too. We are also transitioning to self-contained scrapes and away from the method relying on the source_configs.R method. I am going to close this for now but please submit another issue for anything else you come across (especially if I am wrong about the Yahoo projections)
