### ISSUE TITLE
Issue when Installing

### ISSUE THREAD

**Issue by cdsmithson** [FantasyFootballAnalytics/ffanalytics#73]
When attempting to install with the following command:

`devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics", build_vignettes = TRUE)`

 I get the following:

Downloading GitHub repo FantasyFootballAnalytics/ffanalytics@HEAD
√  checking for file 'C:\Users\blank\AppData\Local\Temp\RtmpE7H0pU\remotes1de3c54a46673\FantasyFootballAnalytics-ffanalytics-ca90952/DESCRIPTION' (802ms)
-  preparing 'ffanalytics':
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
√  creating vignettes (32.8s)
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ffanalytics_2.0.2.0001.tar.gz'
   
* installing *source* package 'ffanalytics' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'tidyverse' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'ffanalytics'
* removing 'C:/Users/blank/Documents/R/R-3.6.1/library/ffanalytics'
Error: Failed to install 'ffanalytics' from GitHub:
  (converted from warning) installation of package ‘C:/Users/blank/AppData/Local/Temp/RtmpE7H0pU/file1de3c363037a1/ffanalytics_2.0.2.0001.tar.gz’ had non-zero exit status

**Comment by kylekyle44** [comment]
Im having the same issue as well! Ive tried multiple different ways to install and can not get it to install either.

**Comment by upsidechristian** [comment]
I'm havin the exact same issue:
`Error: Failed to install 'ffanalytics' from GitHub:
  (converted from warning) installation of package ‘C:/Users/CHRIST~1/AppData/Local/Temp/RtmpgBlj0G/file63346ebc10a3/ffanalytics_2.0.2.0001.tar.gz’ had non-zero exit status`

**Comment by atungate** [comment]
I am going to close this now but please post another issue if there are ever issues installing again
