### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by TheMathNinja** [FantasyFootballAnalytics/ffanalytics#76]
All year scrape_data has been working but this week I get:

scrape_2020_week7 <- scrape_data(
+   src = c("CBS", "ESPN", "FantasyData", "FantasyPros", "FantasySharks", "FFToday",
+           "Yahoo", "FantasyFootballNerd", "NFL"),
+   pos = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"),
+   season = 2020,
+   week = 7
+ )
Scraping QB projections from 
 https://www.cbssports.com/fantasy/football/stats/QB/2020/7/projections/nonppr 
Scraping RB projections from 
 https://www.cbssports.com/fantasy/football/stats/RB/2020/7/projections/nonppr 
Scraping WR projections from 
 https://www.cbssports.com/fantasy/football/stats/WR/2020/7/projections/nonppr 
Scraping TE projections from 
 https://www.cbssports.com/fantasy/football/stats/TE/2020/7/projections/nonppr 
additional arguments ignored in warning()
Error in value[[3L]](cond) : no loop for break/next, jumping to top level
In addition: Warning messages:
1: In request_GET(session, url) : Internal Server Error (HTTP 500).
2: In read_xml.response(x$response, ..., as_html = as_html) :
  Internal Server Error (HTTP 500).

**Comment by TheMathNinja** [comment]
Well now that's gone but I'm getting:

Error in range[1] : object of type 'builtin' is not subsettable
In addition: Warning message:
In .Primitive("as.double")(x, ...) : NAs introduced by coercion

I always got the warnings, but not the error. Still blocking the code.

**Comment by scottfrechette** [comment]
I just submitted a PR that fixed this issue for me, assuming it's when you are calling projections_table()

**Comment by TheMathNinja** [comment]
Thank you! We are back in business!
