### ISSUE TITLE
Issues installing the package

### ISSUE THREAD

**Issue by mdisorbo1** [FantasyFootballAnalytics/ffanalytics#78]
Hello!

When I run:

`devtools::install_github(repo = "FantasyFootballAnalytics/ffanalytics", build_vignettes = TRUE)`

And select the 'update All' option, I get this error:

`rmarkdown (2.3 -> 2.5) [CRAN]`
`Installing 1 packages: rmarkdown`

`  There is a binary version available but the source version is later:`
`          binary source needs_compilation`
`rmarkdown    2.3    2.5             FALSE`

`installing the source package ‘rmarkdown’`

`trying URL 'https://cran.rstudio.com/src/contrib/rmarkdown_2.5.tar.gz'`
`Content type 'application/x-gzip' length 3203415 bytes (3.1 MB)`
`==================================================`
`downloaded 3.1 MB`

`dyld: lazy symbol binding failed: Symbol not found: _utimensat`
`  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)`
`  Expected in: /usr/lib/libSystem.B.dylib`

`dyld: Symbol not found: _utimensat`
`  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)`
`  Expected in: /usr/lib/libSystem.B.dylib`

`/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 14346 Done                    echo 'tools:::.install_packages()'`
`     14347 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}`
`Error: Failed to install 'ffanalytics' from GitHub:`
`  (converted from warning) installation of package ‘rmarkdown’ had non-zero exit status`

I assume it has to do with `rmarkdown`, naturally, but I can't get the package to install. I'm on a Mac; has anyone else seen this issue?

**Comment by atungate** [comment]
I believe it is working now, but please let me know if it is not working on your system!
