### ISSUE TITLE
add_ecr function - add league scoring

### ISSUE THREAD

**Issue by sansbacon** [FantasyFootballAnalytics/ffanalytics#8]
For the add_ecr function, there should be an option for PPR, half PPR, or standard.
The fantasypros URLs are as follows:

STD: https://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php
HPPR: https://www.fantasypros.com/nfl/rankings/half-point-ppr-cheatsheets.php
PPR: https://www.fantasypros.com/nfl/rankings/ppr-cheatsheets.php

**Comment by MrDAndersen** [comment]
The function pulls the rankings based on the league type determined by scoring settings supplied

**Comment by sansbacon** [comment]
Yeah, just noticed that looking at the function code. Thanks!

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
