### ISSUE TITLE
Error running add_ecr()

### ISSUE THREAD

**Issue by RandalMorris** [FantasyFootballAnalytics/ffanalytics#84]
When I run the command below I get the following error.

Error in UseMethod("html_table") : 
  no applicable method for 'html_table' applied to an object of class "xml_missing"

my_projections <- projections_table(my_scrape) %>% 
  add_player_info() %>% add_ecr() %>% add_risk()

**Comment by atungate** [comment]
Hey Randal, I worked on getting the `scrape_ecr()` function working again (which `add_ecr()` calls; PR 85). For me, the `scrape_ecr()` function works as expected but I need update a few things `add_ecr()` function to get it working properly (i.e., it still does not work). Let me know how it works for you.

**Comment by atungate** [comment]
Ahh, just figured it out. The `scrape_ecr()` function pulls in fantasypros numeric id. I will need to add those to our internal id dataframe or pull ECR another way (right now we use a different one). Either way, we'll get it fixed in the next week or two.

**Comment by RandalMorris** [comment]
There is a fantasypros package, but I think they made some changes on the site. It doesn't work this year

**Comment by atungate** [comment]
Hey Randal, should be working correctly now. Can you let me know if you have any more issues?

**Comment by RandalMorris** [comment]
works now thank you.
