### ISSUE TITLE
Excluding players - parameter for projections_table

### ISSUE THREAD

**Issue by sansbacon** [FantasyFootballAnalytics/ffanalytics#9]
There are some zombie projections that it would be helpful to be able to exclude with a parameter to projections_table. For example, Jamaal Charles is projected for 174 points (RB22) and Matt Forte, who is retired, is projected for 155 points (RB 37), which throws off the positional ranks below them. Thanks!

**Comment by MrDAndersen** [comment]
Do you know which sources those projections come from? Note, that if you include FantasyFootballNerd and are not using their API you not getting useful data from them.

**Comment by sansbacon** [comment]
Excluding fantasyfootballnerd did the trick. Thanks!

**Comment by isaactpetersen** [comment]
Posting this here in case anyone is interested in helping with the project:
https://fantasyfootballanalytics.net/2019/09/call-for-help-lead-r-shiny-developer.html
